### ISSUE TITLE
Upgrading to react-router v4?

### ISSUE THREAD

**Issue by cubadomingo** [tmobaird/i-want-to-contribute#18]
any plans to upgrade react-router v4?

**Comment by tmobaird** [comment]
Definitely. I wanted to do a full slate upgrade at some point in the near future, just haven't really gotten to it yet. I wanted to upgrade react, react-dom, react router, react bootstrap all at the same time, but I think react-bootstrap is still adjusting to some of the breaking changes from react 15.5. Do you know what new things were added in react-router v4?

Also you're more than welcome to help out with any of this if you want.
