### ISSUE TITLE
[Docs] Additional Resources

### ISSUE THREAD

**Issue by tmobaird** [tmobaird/i-want-to-contribute#25]
I think we should create an `Additional Resources` doc that includes links to a bunch of other good reference points for learning react and other related topics/tools (redux, webpack, es6, etc). We don't need to fill out this doc all at one time, but create the simple template initially and add to it as we go.

The doc should probably delimited by each topic. For example, in this doc we would probably include a bunch of headers for each topic, with bulleted links within those. Example:

# React

- [Link 1]()
- [Link 2]()

# Redux

- [Link 3]()
- [Link 4]()

**Comment by cubadomingo** [comment]
I'll take it!

**Comment by tmobaird** [comment]
@cubadomingo you got it!

**Comment by tmobaird** [comment]
Closed via #26
