### ISSUE TITLE
Add "Find me on Github" Link to Navbar

### ISSUE THREAD

**Issue by tmobaird** [tmobaird/i-want-to-contribute#51]
In the navbar we should add a link to the github repository.

I'm currently envisioning a link in the right side of navbar that includes some text like `Find me on Github` with the Github logo next to it.

This will help people easily find the repo from the app.

Example:

![image](https://cloud.githubusercontent.com/assets/7366444/26089352/0413dc64-39cb-11e7-8826-307556fbe8a1.png)

**Comment by Ricardo-Silva91** [comment]
Hello, I made a pull request with a proposed solution for this issue (#59).
Feedback is welcome.
