### ISSUE TITLE
Render a message if github returns no results

### ISSUE THREAD

**Issue by cubadomingo** [tmobaird/i-want-to-contribute#67]
If github returns no results then a message or component should be rendered to tell the user no results have been found. Currently it's displaying: 
<img width="828" alt="screen shot 2017-06-04 at 8 38 07 pm" src="https://cloud.githubusercontent.com/assets/15992549/26769701/cc7e965e-4965-11e7-98b6-788977c5ea79.png">

It's basically rendering the SearchResultsBox but showing an empty space because the props.results.data value is empty.

A potential solution is to add `show={this.props.search.submitted && this.props.results.data}` to the SearchResultsBox component inside the SearchPage container and then a conditional to render the message: 

` (!this.props.search.submitted && !this.props.results.data) ? <NoResults /> : ''`

or just remove the show key from the SearchResultsBox and use this:

` (!this.props.search.submitted && !this.props.results.data) ? <NoResults /> : <SearchResultsBox {...props}'`

**Comment by tmobaird** [comment]
@cubadomingo you want this one?
