### ISSUE TITLE
[Docs]: React- State

### ISSUE THREAD

**Issue by tmobaird** [tmobaird/i-want-to-contribute#81]
A State doc already exists for this project's doc book, but is currently an empty place holder until its contents are filled in.

This doc should be updated to include all things state related for react. Including things like:
- What is component state?
- Why is managing state important?
- Why you can't and shouldn't directly mutate state?
- How to set initial state
- How to update a component's state
- How to update a component's state on an event action (preferably with code example)
- How re-rendering works when state changes

**Comment by cubadomingo** [comment]
I'll take this one
