### ISSUE TITLE
console error when running specs locally

### ISSUE THREAD

**Issue by cubadomingo** [tmobaird/i-want-to-contribute#85]
<img width="990" alt="screen shot 2017-08-16 at 1 22 42 pm" src="https://user-images.githubusercontent.com/15992549/29384129-ccc40058-8287-11e7-8b7b-6bead37b0c39.png">

The error is a missing prop error for the MapMarkerPopupInformation component.

**Comment by tmobaird** [comment]
So this is normal actually. I looked at the test cases, and it looks like the purposes of these tests is to check how something functions when a prop is not there, so this is not actually a mocha error, but just a console error raised by the component. The tests for this should still pass. @cubadomingo thoughts?
